services:
  usenet-streamer:
    image: ghcr.io/sanket9225/usenetstreamer:latest
    container_name: usenet-streamer
    restart: unless-stopped
    expose:
      - 7000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usenet-streamer.rule=Host(`${USENET_STREAMER_HOSTNAME?}`)"
      - "traefik.http.routers.usenet-streamer.entrypoints=websecure"
      - "traefik.http.routers.usenet-streamer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.usenet-streamer.middlewares=authelia@docker"
      - "traefik.http.services.usenet-streamer.loadbalancer.server.port=7000"
    profiles:
      - usenet-streamer
      - all
