services:
  altmount:
    image: ghcr.io/javi11/altmount:latest
    container_name: altmount
    restart: unless-stopped
    expose:
      - 8080
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PORT=8080
      - COOKIE_DOMAIN=${ALTMOUNT_HOSTNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.altmount.rule=Host(`${ALTMOUNT_HOSTNAME?}`)"
      - "traefik.http.routers.altmount.entrypoints=websecure"
      - "traefik.http.routers.altmount.tls.certresolver=letsencrypt"
      - "traefik.http.routers.altmount.middlewares=authelia@docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config:/config
    profiles:
      - altmount
      - all

