# yamllint disable rule:line-length
---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  ## change this to the username you want to use
  jaesky:  
    disabled: false
    ## change this to the display name you want to use
    displayname: "jaesky"  
    ## Generate the argon 2 password hash using the following command
    ## sudo docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password 'yourpassword'
    ## (currently the password is 'password')
    password: "$argon2id$v=19$m=65536,t=3,p=4$KIYLbQnxfE8Rt1Yx3h4SfQ$ZW4Gfc/9zKkq3t0B6O8VKr3ZuJvifFXsvOwE3jMbpCE"  
    email: world_of_jae@hotmail.com
    groups:
      - admins
      - dev
...
# yamllint enable rule:line-length
