services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    expose:
      - 5055
    environment:
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`${JELLYSEERR_HOSTNAME?}`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls.certresolver=letsencrypt"
    volumes:
      - ${DOCKER_DATA_DIR}/jellyseerr:/app/config
    depends_on:
      decypharr:
        condition: service_healthy
    profiles:
      - jellyseerr
      - all
